# Generated by Django 4.1.10 on 2023-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
        migrations.AddField(
            model_name='projects',
            name='associated_with',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
